----- FINAL 계정 생성 -----
-- CREATE USER FINAL IDENTIFIED BY FINAL;
-- GRANT RESOURCE, CONNECT TO FINAL;
-----  FINAL 계정 삭제 -----
-- DROP USER FINAL CASCADE;

---------------------------------------------------------------------------
--------------------------- USER 관련 테이블 ---------------------------
---------------------------------------------------------------------------

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER (
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    NAME VARCHAR2(20) NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL UNIQUE,
    PHONE VARCHAR2(13),
    ADDRESS VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);

DROP SEQUENCE SEQ_UNO;
CREATE SEQUENCE SEQ_UNO;

COMMENT ON COLUMN MEMBER.NO IS '사용자 번호';
COMMENT ON COLUMN MEMBER.ID IS '사용자 아이디';
COMMENT ON COLUMN MEMBER.PASSWORD IS '사용자 비밀번호';
COMMENT ON COLUMN MEMBER.ROLE IS '사용자 등급';
COMMENT ON COLUMN MEMBER.NAME IS '사용자 이름';
COMMENT ON COLUMN MEMBER.NICKNAME IS '사용자 닉네임';
COMMENT ON COLUMN MEMBER.PHONE IS '사용자 연락처';
COMMENT ON COLUMN MEMBER.ADDRESS IS '사용자 주소';
COMMENT ON COLUMN MEMBER.STATUS IS '사용자 상태(Y/N)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';


INSERT INTO MEMBER (
    NO, 
    ID, 
    PASSWORD, 
    ROLE,
    NAME, 
    NICKNAME,
    PHONE, 
    ADDRESS, 
    STATUS, 
    ENROLL_DATE, 
    MODIFY_DATE
) VALUES(
    SEQ_UNO.NEXTVAL, 
    'admin', 
    '1234', 
    'ROLE_ADMIN', 
    '관리자', 
    '나의닉네임은무엇일까', 
    '010-1234-5678', 
    '서울시 강남구 역삼동',
    DEFAULT,
    DEFAULT,
    DEFAULT
);

COMMIT;
SELECT * FROM MEMBER;
---------------------------------------------------------------------------
--------------------------- Board 관련 테이블 ---------------------------
---------------------------------------------------------------------------

DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD (	
    NO NUMBER,
    WRITER_NO NUMBER, 
	TITLE VARCHAR2(200), 
	CONTENT VARCHAR2(2000), 
	TYPE VARCHAR2(10), 
	ORIGINAL_FILENAME VARCHAR2(100), 
	RENAMED_FILENAME VARCHAR2(100), 
	READCOUNT NUMBER DEFAULT 0, 
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATE DEFAULT SYSDATE, 
    MODIFY_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT PK_BOARD_NO PRIMARY KEY(NO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO) ON DELETE SET NULL
);

COMMENT ON COLUMN BOARD.NO IS '게시글번호';
COMMENT ON COLUMN BOARD.WRITER_NO IS '게시글 작성자';
COMMENT ON COLUMN BOARD.TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.TYPE IS '게시글 분류';
COMMENT ON COLUMN BOARD.ORIGINAL_FILENAME IS '기존 파일명';
COMMENT ON COLUMN BOARD.RENAMED_FILENAME IS '수정 파일명';
COMMENT ON COLUMN BOARD.READCOUNT IS '조회수';
COMMENT ON COLUMN BOARD.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.MODIFY_DATE IS '게시글 수정일';

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO;

INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 1, '게시글 1',  '게시글
테스트입니다.', '잡담', '원본파일명.txt', '변경된파일명.txt', DEFAULT, 'Y', SYSDATE, SYSDATE);

BEGIN
    FOR N IN 1..30
    LOOP
        INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 1, 'KH 3팀 독서의 민족, 게시글 테스트 '||SEQ_BOARD_NO.CURRVAL||'입니다.','게시글
테스트입니다. '||SEQ_BOARD_NO.CURRVAL, '잡담', null, null, DEFAULT, 'Y', SYSDATE, SYSDATE);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;
SELECT * FROM BOARD;
---------------------------------------------------------------------------
--------------------------- REPLY 관련 테이블 --------------------------
---------------------------------------------------------------------------

DROP TABLE REPLY CASCADE CONSTRAINTS;

CREATE TABLE REPLY(
  NO NUMBER PRIMARY KEY,
  BOARD_NO NUMBER,
  WRITER_NO NUMBER,
  CONTENT VARCHAR2(400),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  CREATE_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  FOREIGN KEY (BOARD_NO) REFERENCES BOARD,
  FOREIGN KEY (WRITER_NO) REFERENCES MEMBER
);

DROP SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_REPLY_NO;

COMMENT ON COLUMN "REPLY"."NO" IS '댓글 번호';
COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '댓글이 작성된 게시글';
COMMENT ON COLUMN "REPLY"."WRITER_NO" IS '댓글 작성자';
COMMENT ON COLUMN "REPLY"."CONTENT" IS '댓글 내용';
COMMENT ON COLUMN "REPLY"."STATUS" IS '상태값(Y/N)';
COMMENT ON COLUMN "REPLY"."CREATE_DATE" IS '댓글 작성일';
COMMENT ON COLUMN "REPLY"."MODIFY_DATE" IS '댓글 수정일';

BEGIN
    FOR N IN 1..30
    LOOP
        INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, N, 1, '안녕하세요.<br>반갑습니다.', DEFAULT, DEFAULT, DEFAULT);
        INSERT INTO REPLY VALUES(SEQ_REPLY_NO.NEXTVAL, N, 1, 'KH 3팀<br>댓글 테스트입니다.', DEFAULT, DEFAULT, DEFAULT);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/
COMMIT;
SELECT * FROM REPLY;
--------------------------------DDL 끝-------------------------------------------